### ISSUE TITLE
Caffe: import option_list ImportError: cannot import name 'option_list'

### ISSUE THREAD

**Issue by sliawatimena** [jed-frey/DIGITS3#10]
Dear all,

My system is Ubuntu 18.04.2 LTS (bionic), amd64, RAM 32 GB, GTX1080.
Python 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] on linux

I edit ~/DIGITS3/MANIFEST.in
(from "digits" changed into "digits3")
```
include requirements*.txt
recursive-include digits3/templates *
recursive-include digits3/static *
recursive-include digits3/standard-networks *
recursive-include digits3/tools/torch *
recursive-include digits3/tools/tensorflow *
recursive-include digits3/extensions *.css
recursive-include digits3/extensions *.html
recursive-include digits3/extensions *.js
include versioneer.py
include digits3/_version.py
```

I make a suggestion for README steps to add **'./run.sh'** before python setup.py build
```
pip install -r requirements.txt # Install requirements. 
./run.sh   # help to avoid a lot of troubles.
python setup.py build # Build DIGITS3
python setup.py develop # "Install" DIGITS3 in development mode.

digits-devserver # Run digits server.
```
All steps in the Readme are ok, except the last command. 

Then I try to visit https://github.com/jed-frey/build_caffe/releases
```
$ wget https://github.com/jed-frey/build_caffe/releases/download/v0.0.1/caffe_dist-99bd99795dcdf0b1d3086a8d67ab1782a8a08383-v0.0.1.tar.xz
$ tar -xJvf caffe_dist-*.tar.xz -C /opt/
$ echo export PATH=\"/opt/caffe/distribute/bin:\$PATH\" >> ${HOME}/.bashrc
$ echo export PYTHONPATH=\"/opt/caffe/distribute/python:\$PYTHONPATH\" >> ${HOME}/.bashrc
```

Please help. Thank you very much in advance.

Warmest Regards,
suryadi

(venv) suryadi@xtal:/media/suryadi/DATA/DIGITS3 **$ digits-devserver**
```
 ██████╗ ██╗ ██████╗ ██╗████████╗███████╗██████╗ 
 ██╔══██╗██║██╔════╝ ██║╚══██╔══╝██╔════╝╚════██╗
 ██║  ██║██║██║  ███╗██║   ██║   ███████╗ █████╔╝
 ██║  ██║██║██║   ██║██║   ██║   ╚════██║ ╚═══██╗
 ██████╔╝██║╚██████╔╝██║   ██║   ███████║██████╔╝
 ╚═════╝ ╚═╝ ╚═════╝ ╚═╝   ╚═╝   ╚══════╝╚═════╝  v0+untagged.1.g0ed95aa.dirty

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/suryadi/DATA/DIGITS3/digits3/__main__.py", line 86, in <module>
    main()
  File "/media/suryadi/DATA/DIGITS3/digits3/__main__.py", line 47, in main
    import digits3.config
  File "/media/suryadi/DATA/DIGITS3/digits3/config/__init__.py", line 23, in <module>
    from . import caffe, gpu_list, jobs_dir, log_file, server_name, store_option, tensorflow, torch, url_prefix
  File "/media/suryadi/DATA/DIGITS3/digits3/config/caffe.py", line 26, in <module>
    from . import option_list
ImportError: cannot import name 'option_list'
(venv) suryadi@xtal:/media/suryadi/DATA/DIGITS3$ 
```

My environment variables are:
```
$ echo $PATH
/opt/caffe/distribute/bin:/media/suryadi/DATA/DIGITS3/venv/bin:/home/suryadi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
$ echo $PYTHONPATH
/opt/caffe/distribute/python:
```

$ python
```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/caffe/distribute/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/opt/caffe/distribute/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libcaffe.so.1.0.0: cannot open shared object file: No such file or directory
>>> 

```

**Comment by jed-frey** [comment]
https://github.com/jed-frey/DIGITS3/blob/master/README.md
